/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudiosIndexRouteImport } from './routes/studios/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as StudiosSlugRouteImport } from './routes/studios/$slug'
import { Route as AdminReservationsRouteImport } from './routes/admin/reservations'
import { Route as AdminDisponibilitesRouteImport } from './routes/admin/disponibilites'
import { Route as AdminConnexionRouteImport } from './routes/admin/connexion'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiosIndexRoute = StudiosIndexRouteImport.update({
  id: '/studios/',
  path: '/studios/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudiosSlugRoute = StudiosSlugRouteImport.update({
  id: '/studios/$slug',
  path: '/studios/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReservationsRoute = AdminReservationsRouteImport.update({
  id: '/admin/reservations',
  path: '/admin/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDisponibilitesRoute = AdminDisponibilitesRouteImport.update({
  id: '/admin/disponibilites',
  path: '/admin/disponibilites',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminConnexionRoute = AdminConnexionRouteImport.update({
  id: '/admin/connexion',
  path: '/admin/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/confirmation': typeof ConfirmationRoute
  '/admin/connexion': typeof AdminConnexionRoute
  '/admin/disponibilites': typeof AdminDisponibilitesRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/studios/$slug': typeof StudiosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/studios/': typeof StudiosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/confirmation': typeof ConfirmationRoute
  '/admin/connexion': typeof AdminConnexionRoute
  '/admin/disponibilites': typeof AdminDisponibilitesRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/studios/$slug': typeof StudiosSlugRoute
  '/admin': typeof AdminIndexRoute
  '/studios': typeof StudiosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/confirmation': typeof ConfirmationRoute
  '/admin/connexion': typeof AdminConnexionRoute
  '/admin/disponibilites': typeof AdminDisponibilitesRoute
  '/admin/reservations': typeof AdminReservationsRoute
  '/studios/$slug': typeof StudiosSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/studios/': typeof StudiosIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/confirmation'
    | '/admin/connexion'
    | '/admin/disponibilites'
    | '/admin/reservations'
    | '/studios/$slug'
    | '/admin/'
    | '/studios/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/confirmation'
    | '/admin/connexion'
    | '/admin/disponibilites'
    | '/admin/reservations'
    | '/studios/$slug'
    | '/admin'
    | '/studios'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/confirmation'
    | '/admin/connexion'
    | '/admin/disponibilites'
    | '/admin/reservations'
    | '/studios/$slug'
    | '/admin/'
    | '/studios/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConfirmationRoute: typeof ConfirmationRoute
  AdminConnexionRoute: typeof AdminConnexionRoute
  AdminDisponibilitesRoute: typeof AdminDisponibilitesRoute
  AdminReservationsRoute: typeof AdminReservationsRoute
  StudiosSlugRoute: typeof StudiosSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  StudiosIndexRoute: typeof StudiosIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studios/': {
      id: '/studios/'
      path: '/studios'
      fullPath: '/studios/'
      preLoaderRoute: typeof StudiosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studios/$slug': {
      id: '/studios/$slug'
      path: '/studios/$slug'
      fullPath: '/studios/$slug'
      preLoaderRoute: typeof StudiosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reservations': {
      id: '/admin/reservations'
      path: '/admin/reservations'
      fullPath: '/admin/reservations'
      preLoaderRoute: typeof AdminReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/disponibilites': {
      id: '/admin/disponibilites'
      path: '/admin/disponibilites'
      fullPath: '/admin/disponibilites'
      preLoaderRoute: typeof AdminDisponibilitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/connexion': {
      id: '/admin/connexion'
      path: '/admin/connexion'
      fullPath: '/admin/connexion'
      preLoaderRoute: typeof AdminConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConfirmationRoute: ConfirmationRoute,
  AdminConnexionRoute: AdminConnexionRoute,
  AdminDisponibilitesRoute: AdminDisponibilitesRoute,
  AdminReservationsRoute: AdminReservationsRoute,
  StudiosSlugRoute: StudiosSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  StudiosIndexRoute: StudiosIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
